{% set version = "0.2.6" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-wdman
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/wdman_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/wdman/wdman_{{ version }}.tar.gz
  sha256: e62ebbe240ef349f5f9486227b80716321b61cd68dd8de3e460c9b1bd3e21c58

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-assertthat
    - r-binman
    - r-processx
    - r-semver >=0.2.0
    - r-yaml
  run:
    - r-base
    - r-assertthat
    - r-binman
    - r-processx
    - r-semver >=0.2.0
    - r-yaml

test:
  commands:
    - $R -e "library('wdman')"           # [not win]
    - "\"%R%\" -e \"library('wdman')\""  # [win]

about:
  home: https://docs.ropensci.org/wdman, https://github.com/ropensci/wdman

  license: MIT
  summary: There are a number of binary files associated with the 'Webdriver'/'Selenium' project (see <http://www.seleniumhq.org/download/>, <https://sites.google.com/a/chromium.org/chromedriver/>, <https://github.com/mozilla/geckodriver>, <http://phantomjs.org/download.html> and <https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver>
    for more information). This package provides functions to download these binaries and to manage processes involving them.

  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
